### ISSUE TITLE
Distribute of arm64 binary of vagrant via this tap

### ISSUE THREAD

**Issue by jottr** [hashicorp/homebrew-tap#233]
The [installation](https://developer.hashicorp.com/vagrant/downloads?product_intent=vagrant) page for vagrant  `2.3.6` shows that there exists an `arm64` version of Vagrant now.  
The cask in this tap only distributes the version for `amd64`.

**Comment by jmuchovej** [comment]
This also applies to the `homebrew-cask` copy.

c.f. https://github.com/Homebrew/homebrew-cask/issues/148665

**Comment by chrisroberts** [comment]
Just to note on this issue, as mentioned in the [linked homebrew issue](https://github.com/Homebrew/homebrew-cask/issues/148665), Vagrant is now built as a universal package and the amd64/arm64 packages are the same. The linked cask updates will add arch specific entries but, with regards to Vagrant at least, won't really matter :slightly_smiling_face:

**Comment by jmuchovej** [comment]
> Vagrant is now built as a universal package and the amd64/arm64 packages are the same.

Right. The main utility of doing like was done with https://github.com/Homebrew/homebrew-cask/pull/148719 was that when looking at what the cask installs, naïvely one would see `...vagrant_amd64...` rather than `...vagrant_arm64...`. Of course, they're the same package, but it makes it seem like Vagrant is installing as an application that needs Rosetta (even though it clearly doesn't).

i.e., my motives for this stem from seeing Vagrant install as an `amd64` app rather than an `arm64` app. Unnecessarily, I spent an insignificant amount of time trying to figure out whether Vagrant was able to run on MacOS without Rosetta – so in the interest of saving others from doing the same, it seems sensible on `arm64` systems to pull the `arm64`-labeled Vagrant _even though the `arm64` and `amd64` packages are the same_.
