### ISSUE TITLE
Support install of specific version

### ISSUE THREAD

**Issue by karlismelderis** [hashicorp/homebrew-tap#79]
Please add support to install specific terraform versions:
`brew install hashicorp/tap/@0.12.24`

Terraform state is sensitive to terraform version that it was generated with and we prefer to keep same version in CI pipelines and local.

**Comment by cotarg** [comment]
Hi @karlismelderis:

Thank you for sharing your use case regarding installing multiple versions via our Homebrew tap.

The current intention for our Homebrew tap is to distribute up to date versions of Hashicorp products. Homebrew does not handle versioning gracefully, relying on the maintenance of a separate formula for every version distributed. Additionally, in their own documentation Homebrew discourage the reliance on versioning whenever possible.

For these reasons we recommend using [releases.hashicorp.com](https://releases.hashicorp.com) to obtain the specific versions you need on demand, as it is not our plan to support versioning by naming convention in our tap at this time. If management via Homebrew is a priority due to your workflow, you may also be able to use a community tool such as [tfenv](https://github.com/tfutils/tfenv) or [chtf](https://github.com/Yleisradio/chtf) that allow you to manage Terraform versions after installing via Homebrew.
